### ISSUE TITLE
Support directly specifying folder URL.

### ISSUE THREAD

**Issue by laosb** [onmyway133/EasyStash#12]
Thank you for your work, but it seems in your code, you just simply construct the folder URL by using the configurable  `FileManager.SearchPathDirectory` and `folder`. However, it will be a lot better if you can just have an option for me to directly set a URL since `FileManager` API is robust and easy to use enough, and your options don't directly support situations like App Group Containers, which I believe is somewhat a must for apps with extensions.

**Comment by onmyway133** [comment]
@laosb Hi, good point, I like this idea. How do you want the API to be?

**Comment by laosb** [comment]
I guess adding a new option `url` in `Option` is good enough. Make sure to alert people when both `url` and the old two exists.
