### ISSUE TITLE
Public method to get fileUrl

### ISSUE THREAD

**Issue by kchlebus** [onmyway133/EasyStash#13]
It's possible to get `fileUrl` by getting `folderUrl` and appending `fileName` to it but I've noticed that this code already exists inside `Storage` but it's not a public method.

```swift
func fileUrl(forKey key: String) -> URL {
    return folderUrl.appendingPathComponent(key, isDirectory: false)
}
```

I think it would be nice to make it public so that it will be convenient to get `fileUrl` by just using it. It could be even computed property. Another approach is to return `fileUrl` from `save` method.

**Comment by onmyway133** [comment]
@kchlebus Hi, I think it would be simple to just make that method public if what's you're interested in is the fileUrl. Would you mind making a PR for that?

**Comment by onmyway133** [comment]
@kchlebus Hi, I will make fileUrl public and make new release
