### ISSUE TITLE
TvOS Crash!

### ISSUE THREAD

**Issue by NikKovIos** [onmyway133/EasyStash#14]
If i use tvos on a REAL device, it crash with description:

 Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=513 "У Вас нет разрешения на сохранение файла «Application Support» в папке «Library»." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/BFD14D85-021C-4A4E-8DBE-A63E386CE6DD/Library/Application Support, NSUnderlyingError=0x28010b630 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}: , line 14

```swift
storage = try! Storage(options: options)
```

-----
Fixed with:
```
options.searchPathDirectory = .cachesDirectory
```

**Comment by onmyway133** [comment]
@NikKovIos Hi, that's a known issue, would you mind making a PR to fix this for tvOS?

**Comment by NikKovIos** [comment]
@onmyway133 sorry, i don't think so.

**Comment by onmyway133** [comment]
I will dad the fix and make new release. Thanks for reporting
