### ISSUE TITLE
Option to bypass in-memory cache

### ISSUE THREAD

**Issue by bellebethcooper** [onmyway133/EasyStash#16]
I'm using EasyStash to store some data in my iOS app, and I want to re-use that data in an iOS 14 widget. It seems like the widget and the app use different memory, so when the app updates the cache, the widget continues using the old data from its in-memory cache, which hasn't been updated, but the newer data *is* available to the widget from the on-disk cache. My current workaround is to add an option to `Options` to bypass the in-memory cache, and based on that `Bool`, only ever look up the key in the on-disk cache for my widget.

Just wondering if it's worth a PR for this, or if there's a better way to do it?

**Comment by onmyway133** [comment]
@bellebethcooper Hi, that's a valid concern. I think with the current codebase, it's not that hard to add a flag to Options to bypass memory cacche.

**Comment by bellebethcooper** [comment]
@onmyway133 Cool, I'll put together a PR then. Thanks!
