### ISSUE TITLE
request to update pod version to 1.1.4

### ISSUE THREAD

**Issue by piemonte** [onmyway133/EasyStash#7]
request to update pod version to 1.1.4

**Comment by piemonte** [comment]
great library too btw 🙌

**Comment by onmyway133** [comment]
@piemonte hi, thanks, do you want to make a PR? I initially try to support only SPM now

**Comment by onmyway133** [comment]
@piemonte Hi, just published on cocoapods. So glad that you find this library useful ❤️ 

> EasyStash (1.1.4) successfully published
