### ISSUE TITLE
Archive to Appstore Connect fails: Info.plist file is missing

### ISSUE THREAD

**Issue by yspreen** [onmyway133/EasyStash#9]
```
This bundle Payload/<app>/Frameworks/EasyStash.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
```

**Comment by onmyway133** [comment]
@yspreen Hi, did you use EasyStash with SPM, CocoaPods or Carthage?

**Comment by yspreen** [comment]
Hey, I'm using carthage.

**Comment by yspreen** [comment]
I'm trying to fix this issue myself right now, but as far as I can tell the key is there. It's set to 
```
$(CURRENT_PROJECT_VERSION)
```

Maybe carthage does not like that?

**Comment by onmyway133** [comment]
@yspreen Hi, I don't have good experience with Carthage as I used mainly CocoaPods. Now I'm switching to SPM

**Comment by yspreen** [comment]
Do you think setting it to a fixed 1.0 would be good?

edit: Wasn't necessary.

**Comment by yspreen** [comment]
I'm investigating whether setting the Build number in Xcode does the trick.

edit: It does

**Comment by yspreen** [comment]
#10 does it!

**Comment by yspreen** [comment]
Would you mind creating a new release? @onmyway133

**Comment by onmyway133** [comment]
@yspreen Hi, here you are https://github.com/onmyway133/EasyStash/releases/tag/1.1.6
